### ISSUE TITLE
Inverted spectrograms quieter than original audio

### ISSUE THREAD

**Issue by QEDan** [andimarafioti/tifresi#1]
Thanks for the great library. The inversions sound good, but I find that they are quieter than the original audio. For example,

```python
import numpy as np
import soundfile as sf
from tifresi.stft import GaussTruncTF
from tifresi.transforms import log_spectrogram, inv_log_spectrogram
from tifresi.utils import preprocess_signal


def pghi_spec_and_invert(audio,
                         hop_size=256,
                         stft_channels=1024):
    audio = preprocess_signal(audio)
    anStft = GaussTruncTF(hop_size=hop_size, stft_channels=stft_channels)
    log_spec = log_spectrogram(anStft.spectrogram(audio[:]))
    audio_inv = anStft.invert_spectrogram(inv_log_spectrogram(log_spec))
    return audio_inv

audio_file = 'p234_132.wav'
audio, _ = sf.read(audio_file)
audio = audio[:90112]

audio_inv = pghi_spec_and_invert(audio)

print(f'Original Audio RMS: {np.sqrt(np.mean(np.square(audio)))}')
print(f'Recovered Audio RMS: {np.sqrt(np.mean(np.square(audio_inv)))}')
```

When I test it on a sample speech audio file using the above code, I get the following results for the RMS values:
```
Original Audio RMS: 0.06201285030860396
Recovered Audio RMS: 0.019518413376684012
```

In this example, the audio recovered from the spectrogram sounds good, but is significantly quieter. I find this same result across all types of files I've tried. Is there a step missing in my script, such as a normalization step? Is there anything you can recommend to get results that are closer to the original audio in amplitude? Thanks in advance!

**Comment by nperraud** [comment]
Hi @QEDan 
The current transform actually loses a global amplitude factor for normalisation reasons. This normalisation is however not necessary.

The simple solution is to simply save the RMS when you do the transform and renormalise afterward. 

The more complicated solution is to modify our transform to not do the normalisation. Just note that in general neural network like stuff of the same amplitude.

Good luck

**Comment by QEDan** [comment]
I see. Thank you so much for explaining! For now, I will store the RMS value and rescale after the transformation as you suggested.
